ALTER TABLE PROJECT ALTER COUNTER RENAME TO SEQ;
ALTER TABLE REPORT ADD SEQ BIGINT;
UPDATE REPORT SET SEQ = CONVERT(SUBSTR(KEY,POSITION('-',KEY)+1),INT);
UPDATE REPORT SET KEY=SUBSTR(KEY,0,POSITION('-',KEY)-1);