SELECT MAIL_CONDITION.ID,MAILACCOUNT.ACCOUNTID,MAIL_CONDITION.PROJECTID,MAIL_CONDITION.COMMENT,MAIL_CONDITION.STARTMAIL,MAIL_CONDITION.PROCESSMAIL,MAIL_CONDITION.ENDMAIL,ACCOUNT.ID as ID_0,ACCOUNT.MAILADDR as MAILADDR_0
FROM
(
 SELECT DISTINCT ACCOUNTID 
 FROM ACCOUNT_GROUPBASE
 WHERE GROUPBASEID IN 
 (
  SELECT GROUPBASEID 
  FROM PROJECT_GROUPBASE 
  WHERE PROJECTID = /*projectid*/
 )
) MAILACCOUNT 
LEFT OUTER JOIN ACCOUNT ON MAILACCOUNT.ACCOUNTID = ACCOUNT.ID
LEFT OUTER JOIN 
MAIL_CONDITION
ON MAIL_CONDITION.ACCOUNTID = MAILACCOUNT.ACCOUNTID AND MAIL_CONDITION.PROJECTID = /*projectid*/
