SELECT ID,NAME,ICON,TRANSITION,ASSIGNFLAG,RESOLUTIONFLAG,DESCRIPTION,RDATE,UDATE
FROM STATUS
WHERE ID NOT IN(
 SELECT STATUSID
 FROM WORKFLOW_STATUS
 WHERE WORKFLOWID = /*workflowid*/
)
AND DELFLAG = FALSE
ORDER BY ID
