SELECT ID,NAME,ICON,TRANSITION,ASSIGNFLAG,RESOLUTIONFLAG,DESCRIPTION,RDATE,UDATE
FROM STATUS
WHERE ID IN (
 SELECT STATUSID
 FROM
  WORKFLOW_STATUS
 WHERE ID IN
 (
  SELECT Nextstatus.NEXTSTATUSID
  FROM WORKFLOW_STATUS WorkflowStatus JOIN NEXTSTATUS Nextstatus ON WorkflowStatus.ID = Nextstatus.WORKFLOWSTATUSID
  WHERE WorkflowStatus.WORKFLOWID = /*workflowid*/ AND WorkflowStatus.STATUSID = /*statusid*/
 )
)
